name: tmdb
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.1.0+27

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  photo_view: ^0.15.0
  google_mobile_ads: ^5.3.1
  firebase_core: ^3.13.0
  get_it: ^8.0.3
  firebase_remote_config: ^5.4.3
  firebase_app_check: ^0.3.2+5
  device_info_plus: ^11.3.3
  package_info_plus: ^8.3.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.3
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  cached_network_image: ^3.4.1
  cloud_functions: ^5.4.0
  android_id: ^0.4.0
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  drift_dev: ^2.26.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900

  assets:
    - .env
    - assets/icons/youtube_logo.png
    - assets/icons/tmdb_logo.png
    - assets/illustrations/internet_connection_error_light.png
    - assets/illustrations/internet_connection_error_dark.png
    - assets/illustrations/unknown_error_light.png
    - assets/illustrations/unknown_error_dark.png
    - assets/illustrations/search_results_not_found_light.png
    - assets/illustrations/search_results_not_found_dark.png
    - assets/illustrations/server_error_light.png
    - assets/illustrations/server_error_dark.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
